[package]
name = "drawnn"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
crossterm = "0.28.1"
ratatui = "0.29.0"
csv = "1.1"
rayon = "1.5"
rand_distr = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rusty_net = { path = "../rusty_net" }